# Order Service Configuration
server.port=8083
spring.application.name=order-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/order_service_db

# Actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Product Service Configuration
product.service.url=http://localhost:8082 